# Generated by Django 5.0.3 on 2024-04-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion ')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificacion ')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('delegado', models.CharField(max_length=150, null=True)),
                ('foto_delegado', models.ImageField(blank=True, null=True, upload_to='img_delegados')),
                ('logo_equipo', models.ImageField(blank=True, null=True, upload_to='logo_equipos')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='campeonatos.grupos')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
