# Generated by Django 5.0.2 on 2024-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='delegado',
        ),
        migrations.RemoveField(
            model_name='historicalequipos',
            name='delegado',
        ),
        migrations.AddField(
            model_name='equipos',
            name='foto_delegado',
            field=models.ImageField(blank=True, null=True, upload_to='img_delegados'),
        ),
        migrations.AddField(
            model_name='historicalequipos',
            name='foto_delegado',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
