# Generated by Django 5.0.2 on 2024-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipos_delegado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='delegado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipos',
            name='delegado',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
