# Generated by Django 5.0.3 on 2024-03-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_grupos_historicalgrupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='grupos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='equipos.grupos'),
        ),
        migrations.AddField(
            model_name='historicalequipos',
            name='grupos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipos.grupos'),
        ),
    ]
