# Generated by Django 5.0.3 on 2024-03-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_grupos_historicalgrupos'),
        ('equipos', '0006_equipos_grupos_historicalequipos_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalequipos',
            name='grupos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='campeonatos.grupos'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='grupos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='campeonatos.grupos'),
        ),
        migrations.RemoveField(
            model_name='historicalgrupos',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Grupos',
        ),
        migrations.DeleteModel(
            name='HistoricalGrupos',
        ),
    ]
