# Generated by Django 5.0.3 on 2024-04-08 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='historical_mails',
            new_name='Historical_Emails',
        ),
        migrations.RenameModel(
            old_name='Historicalhistorical_mails',
            new_name='HistoricalHistorical_Emails',
        ),
    ]
