# Generated by Django 5.0.3 on 2024-04-28 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 4, 28, 1, 16, 29, 17869, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
