# Generated by Django 5.0.2 on 2024-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
