# Generated by Django 5.0.3 on 2024-04-29 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
        ('equipos', '0002_remove_equipos_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion ')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificacion ')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.grupos')),
            ],
            options={
                'verbose_name': 'Equipo_grupo',
                'verbose_name_plural': 'Equipos_Grupos',
                'db_table': 'Equipo_grupo',
            },
        ),
    ]
