# Generated by Django 5.0.3 on 2024-04-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgrupos',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCampeonato',
        ),
        migrations.DeleteModel(
            name='HistoricalGrupos',
        ),
    ]
