# Generated by Django 5.0.2 on 2024-02-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_alter_campeonato_options_remove_campeonato_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcampeonato',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Campeonato', 'verbose_name_plural': 'historical Campeonatos'},
        ),
        migrations.AddField(
            model_name='campeonato',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalcampeonato',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
