# Generated by Django 5.0.3 on 2024-04-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_equipogrupo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campeonato',
            table='campeonatos',
        ),
        migrations.AlterModelTable(
            name='grupos',
            table='grupos',
        ),
    ]
