# Generated by Django 5.0.3 on 2024-04-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_alter_campeonato_table_alter_grupos_table'),
        ('equipos', '0002_remove_equipos_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='campeonato',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato'),
        ),
        migrations.CreateModel(
            name='EquiposCampeonatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion ')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificacion ')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos')),
            ],
            options={
                'verbose_name': 'Campeonato_Equipo',
                'verbose_name_plural': 'Campeonato_Equipos',
                'db_table': 'equipos_campeonato',
            },
        ),
    ]
