# Generated by Django 5.0.3 on 2024-04-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion ')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha Modificacion ')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha Eliminacion')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('num_telefono', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Arbitro',
                'verbose_name_plural': 'Arbitros',
            },
        ),
    ]
