# Generated by Django 5.0.3 on 2024-04-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgoles',
            name='encuentro',
        ),
        migrations.RemoveField(
            model_name='historicalgoles',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgoles',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='historicalsancion',
            name='encuentro',
        ),
        migrations.RemoveField(
            model_name='historicalsancion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsancion',
            name='jugador',
        ),
        migrations.DeleteModel(
            name='HistoricalEncuentro',
        ),
        migrations.DeleteModel(
            name='HistoricalGoles',
        ),
        migrations.DeleteModel(
            name='HistoricalSancion',
        ),
    ]
