# Generated by Django 5.0.2 on 2024-02-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitro',
            options={'verbose_name': 'Arbitro', 'verbose_name_plural': 'Arbitros'},
        ),
        migrations.AlterModelOptions(
            name='encuentro',
            options={'verbose_name': 'Encuentro', 'verbose_name_plural': 'Encuentros'},
        ),
        migrations.AlterModelOptions(
            name='goles',
            options={'verbose_name': 'Goles', 'verbose_name_plural': 'Goles'},
        ),
        migrations.AlterModelOptions(
            name='historicalarbitro',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Arbitro', 'verbose_name_plural': 'historical Arbitros'},
        ),
        migrations.AlterModelOptions(
            name='historicalencuentro',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Encuentro', 'verbose_name_plural': 'historical Encuentros'},
        ),
        migrations.AlterModelOptions(
            name='historicalgoles',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Goles', 'verbose_name_plural': 'historical Goles'},
        ),
        migrations.AlterModelOptions(
            name='historicalsancion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sancion', 'verbose_name_plural': 'historical Sanciones'},
        ),
        migrations.AlterModelOptions(
            name='sancion',
            options={'verbose_name': 'Sancion', 'verbose_name_plural': 'Sanciones'},
        ),
    ]
