# Generated by Django 5.0.2 on 2024-03-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuentros', '0002_alter_arbitro_options_alter_encuentro_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbitro',
        ),
        migrations.DeleteModel(
            name='HistoricalArbitro',
        ),
    ]
