# Generated by Django 5.0.2 on 2024-03-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitros', '0001_initial'),
        ('encuentros', '0003_delete_arbitro_delete_historicalarbitro'),
        ('jugadores', '0003_alter_jugadores_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='arbitros',
            field=models.ManyToManyField(to='arbitros.arbitro'),
        ),
        migrations.AlterField(
            model_name='goles',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='encuentros.encuentro'),
        ),
        migrations.AlterField(
            model_name='goles',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_jugador', to='jugadores.jugadores'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='encuentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='encuentros.encuentro'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sancion_jugador', to='jugadores.jugadores'),
        ),
    ]
