# Generated by Django 5.0.2 on 2024-03-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0003_alter_campeonato_options_and_more'),
        ('encuentros', '0004_encuentro_arbitros_alter_goles_encuentro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='campeonatos.campeonato'),
        ),
    ]
