# Generated by Django 5.0.2 on 2024-02-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaljugadores',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Jugador', 'verbose_name_plural': 'historical Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='jugadores',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
    ]
