# Generated by Django 5.0.2 on 2024-03-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipos_delegado_historicalequipos_delegado'),
        ('jugadores', '0002_alter_historicaljugadores_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipos'),
        ),
    ]
