# Generated by Django 5.0.3 on 2024-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_alter_jugadores_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljugadores',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaljugadores',
            name='foto',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/foto'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='imagen_dni',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/dni'),
        ),
    ]
